apiVersion: v1
kind: Service
metadata:
  name: auth-server-service
  labels:
    app: messenger.auth-server
spec:
  ports:
    - protocol: TCP
      port: 4000
  selector:
    app: messenger.auth-server
